name: Build and Package Speed Test Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --name SPEEDTEST main.py

    - name: List dist directory (debugging)
      run: |
        ls dist
      if: runner.os == 'Linux'

    - name: List dist directory (debugging)
      run: |
        dir dist
      if: runner.os == 'Windows'

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SPEEDTEST-${{ matrix.os }}
        path: dist/SPEEDTEST*
