name: Build and Package Speed Test Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.x']

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile popup.py
        env:
          # Linuxではビルド時に必要となるLC_ALL環境変数を設定a
          LC_ALL: C.UTF-8

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: speed_test_executable-${{ matrix.os }}
          path: |
            dist/speed_test.exe
            dist/speed_test
